version: '3.9'

services:
  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: food-root-servir:latest

    ports:
      - "8081:8080"
    depends_on:
      - db
      - redis
    environment:
      DB_IP: ${DB_IP}
      DB_PORT : ${DB_PORT}
      DB_NAME : ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      JWT_SECRET: ${JWT_SECRET}
      YC_ACCESS_KEY: ${YC_ACCESS_KEY}
      YC_SECRET_KEY: ${YC_SECRET_KEY}

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5431:5432"
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"

volumes:
  db-data:
